apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  labels:
    app: todoapp
spec:
  containers:
  - name: todo-app
    image: stolek/dotnet-todo-main:latest
    ports:
    - containerPort: 8080
