namespace: test-environment

image:
  repository: stolek/dotnet-todo-main
  tag: latest

service:
  name: todoapp-svc
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30001
  app: todoapp  
  protocol: TCP 

deployment:
  name: todoapp-deployment
  replicas: 2
  containerPort: 8080
  app: todoapp
