name: Minikube Helm Deploy Workflow
on:
  workflow_dispatch:

jobs:
  install_minikube:
    runs-on: ubuntu-latest
    name: Install Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
      
      - name: Minikube status
        run: minikube status

  build_and_push_image:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: install_minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-todo-main:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-todo-main:latest

  helm_deploy:
    runs-on: ubuntu-latest
    name: Helm Deploy
    needs: [install_minikube, build_and_push_image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Deploy Helm chart
        run: |
          helm install todo-app-v1 helmtodoapp/todoapp-0.1.0.tgz
  test_deployed_app:
    runs-on: ubuntu-latest
    name: Test Deployed App
    needs: [install_minikube, build_and_push_image, helm_deploy]
    steps:
      - name: Get resources in the namespace
        run: |
          kubectl get pods -A
          kubectl get svc -A  

      - name: Wait for Pod to be ready
        run: kubectl wait --for=condition=Ready pod/todoapp-pod --timeout=300s

      - name: Curl the endpoint
        run: |
          curl "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"

      - name: Curl PUT data 
        run: |
          curl -X PUT -H "Content-Type: application/json" -d '{"name":"Dog","description":"dog is walking"}' "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"

      - name: Curl the endpoint again 
        run: |
          curl "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"          
