name: Minikube workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Install Minikube, Deploy App & Test
    steps:
      - uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
      
      - name: Minikube status
        run: minikube status

      - name: Build and push Docker image from Dockerfile
        run: |
          docker build -t  dotnet-todo-main:latest .
          docker tag dotnet-todo-main:latest stolek/dotnet-todo-main:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login myregistry -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push myreg/myapp:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy/pod.yml
          kubectl apply -f deploy/service.yml

      - name: Get resources in the namespace
        run: |
          kubectl get pods -A
          kubectl get svc -A  

      - name: Wait for Pod to be ready
        run: kubectl wait --for=condition=Ready pod/todoapp-pod --timeout=300s

      - name: Curl the endpoint
        run: |
          curl "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"

      - name: Curl PUT data 
        run: |
           curl -X PUT -H "Content-Type: application/json" -d '{"name":"Dog","description":"dog is walking"}' "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"

      - name: Curl the endpoint again 
        run: |
          curl "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"
