name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run version bumping script
        id: bump_version
        run: |
          export NEW_VERSION=$(bash versioning.sh)
          echo "New version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create and push tag
        run: |
          git config --local user.email "stole_kostadinovski@hotmail.com"
          git config --local user.name "stolekostadinovski"
          git tag -a ${{ steps.bump_version.outputs.new_version }} -m "Version ${{ steps.bump_version.outputs.new_version }}"
          git push origin ${{ steps.bump_version.outputs.new_version }}
